import type { Deal } from "./types";

export const deals: Deal[] = [
  {
    id: "meridian",
    code: "PROJ-MERIDIAN",
    borrowerName: "Meridian Surgical Partners",
    description:
      "Multi-site ambulatory surgery center platform serving the Southeast US, with 18 ASCs across 4 states and ~$112MM of LTM revenue.",
    sector: "Healthcare",
    geography: "United States (Southeast)",
    stage: "IC Review",
    sponsor: {
      name: "Westview Capital Partners IV",
      type: "Sponsor-backed",
      fundSize: 2400,
    },
    useOfProceeds: "LBO",
    totalDealSizeMM: 285,
    ourCommitmentMM: 165,
    financials: [
      { label: "FY22", revenue: 78.4, ebitda: 14.1, ebitdaMargin: 18.0 },
      { label: "FY23", revenue: 96.2, ebitda: 19.8, ebitdaMargin: 20.6 },
      { label: "LTM", revenue: 112.5, ebitda: 24.3, ebitdaMargin: 21.6 },
      { label: "FY24E", revenue: 128.0, ebitda: 28.9, ebitdaMargin: 22.6 },
    ],
    ltmEbitda: 24.3,
    ltmRevenue: 112.5,
    totalLeverage: 5.45,
    seniorLeverage: 5.45,
    ltv: 48,
    fixedChargeCoverage: 1.85,
    blendedYield: 11.4,
    blendedSpread: 625,
    capitalStructure: [
      {
        id: "rcf",
        name: "Revolver",
        type: "Revolver",
        amountMM: 25,
        rate: "S+500",
        floor: "1.00%",
        maturityYears: 5,
        seniority: 1,
        ourHoldMM: 15,
        call: "NC, par",
      },
      {
        id: "ut",
        name: "Senior Secured Unitranche",
        type: "Unitranche",
        amountMM: 165,
        rate: "S+625",
        floor: "1.00%",
        oid: "2.00%",
        maturityYears: 6,
        seniority: 1,
        ourHoldMM: 150,
        call: "NC1, 102, 101",
      },
      {
        id: "eq",
        name: "Sponsor Equity",
        type: "Equity",
        amountMM: 95,
        rate: "—",
        maturityYears: 0,
        seniority: 99,
      },
    ],
    diligence: [
      {
        id: "1",
        workstream: "Financial",
        task: "QofE review (Alvarez & Marsal)",
        owner: "S. Park",
        status: "Complete",
        dueDate: "2026-04-12",
      },
      {
        id: "2",
        workstream: "Financial",
        task: "Management projection model build",
        owner: "S. Park",
        status: "Complete",
        dueDate: "2026-04-18",
      },
      {
        id: "3",
        workstream: "Legal",
        task: "Credit agreement first markup",
        owner: "Latham",
        status: "Complete",
        dueDate: "2026-04-22",
      },
      {
        id: "4",
        workstream: "Legal",
        task: "Lien search and corporate diligence",
        owner: "Latham",
        status: "In Progress",
        dueDate: "2026-05-08",
      },
      {
        id: "5",
        workstream: "Commercial",
        task: "Payor mix and reimbursement analysis",
        owner: "L.E.K.",
        status: "Complete",
        dueDate: "2026-04-15",
      },
      {
        id: "6",
        workstream: "Commercial",
        task: "Same-store volume sensitivity",
        owner: "L.E.K.",
        status: "In Progress",
        dueDate: "2026-05-06",
      },
      {
        id: "7",
        workstream: "Operational",
        task: "Site visits — Atlanta and Charlotte",
        owner: "M. Chen",
        status: "Complete",
        dueDate: "2026-04-09",
      },
      {
        id: "8",
        workstream: "ESG",
        task: "Patient safety / outcomes review",
        owner: "M. Chen",
        status: "Flagged",
        dueDate: "2026-05-02",
        notes:
          "One ASC had a CMS deficiency citation in 2023 — remediated, but worth noting for IC.",
      },
      {
        id: "9",
        workstream: "Tax",
        task: "Tax structuring memo (PwC)",
        owner: "PwC",
        status: "In Progress",
        dueDate: "2026-05-10",
      },
      {
        id: "10",
        workstream: "Insurance",
        task: "Malpractice coverage adequacy review",
        owner: "Marsh",
        status: "Complete",
        dueDate: "2026-04-25",
      },
    ],
    risks: [
      {
        category: "Market",
        severity: "Medium",
        description:
          "Reimbursement risk — ~38% of revenue is Medicare; rate compression of 200–300 bps possible over hold.",
        mitigant:
          "Modeled flat reimbursement; sponsor has procedure-mix shift initiatives toward higher-acuity cases.",
      },
      {
        category: "Operational",
        severity: "Medium",
        description: "Physician retention at acquired ASCs.",
        mitigant:
          "60% of physicians have rolled equity; 5-year non-competes for top 20 producers.",
      },
      {
        category: "Credit",
        severity: "Low",
        description: "Leverage of 5.45x is at upper end of historical comps.",
        mitigant:
          "Strong fixed-charge coverage (1.85x); de-levering to 4.2x within 24 months in base case.",
      },
      {
        category: "ESG",
        severity: "Low",
        description: "Prior CMS deficiency citation at one site.",
        mitigant: "Fully remediated; corrective action plan reviewed with Sponsor.",
      },
    ],
    keyTerms: [
      { label: "Maturity", value: "6 years (UT), 5 years (RCF)" },
      { label: "Amortization", value: "1% per annum (UT)" },
      { label: "Call Protection", value: "NC1, 102, 101" },
      { label: "MFN", value: "100 bps for 24 months" },
      { label: "Excess Cash Flow Sweep", value: "75% / 50% / 25%" },
      { label: "Equity Cure", value: "5 cures, 2 consecutive max" },
    ],
    covenants: [
      { name: "Total Net Leverage", threshold: "≤ 6.50x", cushion: "35% cushion to base case" },
      { name: "Fixed Charge Coverage", threshold: "≥ 1.20x", cushion: "54% cushion to base case" },
      { name: "Capex limit", threshold: "$12MM annual" },
    ],
    expectedClose: "2026-06-15",
    leadAnalyst: "S. Park",
    thesis:
      "Defensive healthcare services platform with strong unit economics, founder-physician alignment, and a credible buy-and-build runway. Senior secured unitranche position with attractive coupon and structural protections supports a low-LTV, high-current-yield credit thesis.",
  },
  {
    id: "atlas",
    code: "PROJ-ATLAS",
    borrowerName: "Atlas Logistics Holdings",
    description:
      "Asset-light cross-border freight brokerage with proprietary load-matching technology, ~$340MM net revenue.",
    sector: "Industrials",
    geography: "North America",
    stage: "Diligence",
    sponsor: {
      name: "Brentwood Equity Partners",
      type: "Sponsor-backed",
      fundSize: 1800,
    },
    useOfProceeds: "Refinancing",
    totalDealSizeMM: 410,
    ourCommitmentMM: 200,
    financials: [
      { label: "FY22", revenue: 412, ebitda: 38, ebitdaMargin: 9.2 },
      { label: "FY23", revenue: 366, ebitda: 31, ebitdaMargin: 8.5 },
      { label: "LTM", revenue: 340, ebitda: 36, ebitdaMargin: 10.6 },
      { label: "FY24E", revenue: 372, ebitda: 44, ebitdaMargin: 11.8 },
    ],
    ltmEbitda: 36,
    ltmRevenue: 340,
    totalLeverage: 4.85,
    seniorLeverage: 3.95,
    ltv: 52,
    fixedChargeCoverage: 1.72,
    blendedYield: 11.9,
    blendedSpread: 650,
    capitalStructure: [
      {
        id: "rcf",
        name: "ABL Revolver",
        type: "Revolver",
        amountMM: 50,
        rate: "S+275",
        floor: "0.50%",
        maturityYears: 5,
        seniority: 1,
      },
      {
        id: "tlb",
        name: "Senior Secured Term Loan",
        type: "Term Loan B",
        amountMM: 140,
        rate: "S+550",
        floor: "1.00%",
        oid: "1.50%",
        maturityYears: 7,
        seniority: 1,
        ourHoldMM: 80,
        call: "101 soft call (6 mo)",
      },
      {
        id: "sl",
        name: "Second Lien Term Loan",
        type: "Second Lien",
        amountMM: 35,
        rate: "S+875",
        floor: "1.00%",
        oid: "2.50%",
        maturityYears: 8,
        seniority: 2,
        ourHoldMM: 35,
        call: "NC2, 103, 102, 101",
      },
      {
        id: "eq",
        name: "Sponsor Equity (rolled)",
        type: "Equity",
        amountMM: 185,
        rate: "—",
        maturityYears: 0,
        seniority: 99,
      },
    ],
    diligence: [
      {
        id: "1",
        workstream: "Financial",
        task: "QofE — KPMG",
        owner: "S. Aggarwal",
        status: "In Progress",
        dueDate: "2026-05-14",
      },
      {
        id: "2",
        workstream: "Commercial",
        task: "Top-25 customer reference calls",
        owner: "Bain",
        status: "In Progress",
        dueDate: "2026-05-12",
      },
      {
        id: "3",
        workstream: "Operational",
        task: "Tech platform diligence",
        owner: "PwC",
        status: "Complete",
        dueDate: "2026-04-28",
      },
      {
        id: "4",
        workstream: "Legal",
        task: "Credit doc negotiation",
        owner: "Kirkland",
        status: "In Progress",
        dueDate: "2026-05-20",
      },
      {
        id: "5",
        workstream: "ESG",
        task: "Driver classification / DOL exposure",
        owner: "M. Chen",
        status: "Flagged",
        dueDate: "2026-05-09",
        notes: "AB5 exposure in CA — quantifying potential reclassification cost.",
      },
    ],
    risks: [
      {
        category: "Market",
        severity: "High",
        description: "Freight brokerage cyclicality — coming off a multi-year downturn.",
        mitigant:
          "LTM trough EBITDA used as base; recovery scenario sensitized to flat 2024 spot rates.",
      },
      {
        category: "Operational",
        severity: "Medium",
        description: "Customer concentration — top 10 = 41% of net revenue.",
        mitigant: "Average tenure 7+ years; multi-year MSAs with top 5.",
      },
      {
        category: "Legal",
        severity: "Medium",
        description: "Driver classification exposure (AB5 in California).",
        mitigant: "Reserve sized in projections; structural fix in process.",
      },
    ],
    keyTerms: [
      { label: "Maturity", value: "7 years (TLB), 8 years (2L), 5 years (RCF)" },
      { label: "Amortization", value: "1% (TLB), 0% (2L)" },
      { label: "Call Protection", value: "TLB: 101 soft call; 2L: NC2, 103/102/101" },
      { label: "MFN", value: "75 bps for 18 months (TLB)" },
    ],
    covenants: [
      { name: "Total Net Leverage", threshold: "≤ 5.75x", cushion: "16% cushion" },
      { name: "Springing Fixed Charge (RCF)", threshold: "≥ 1.10x" },
    ],
    expectedClose: "2026-07-08",
    leadAnalyst: "S. Aggarwal",
    thesis:
      "Defensive cash-flow business at trough multiple with structural tailwinds. Senior secured TLB hold with conservative attachment point; second-lien sleeve picks up incremental yield with structural cushion.",
  },
  {
    id: "kestrel",
    code: "PROJ-KESTREL",
    borrowerName: "Kestrel Software, Inc.",
    description:
      "Vertical SaaS platform for property and casualty insurance MGAs, ~$78MM ARR with 116% net retention.",
    sector: "Software",
    geography: "United States",
    stage: "Diligence",
    sponsor: {
      name: "Northbridge Growth Equity III",
      type: "Sponsor-backed",
      fundSize: 1200,
    },
    useOfProceeds: "Acquisition Financing",
    totalDealSizeMM: 175,
    ourCommitmentMM: 110,
    financials: [
      { label: "FY22", revenue: 41, ebitda: 5.2, ebitdaMargin: 12.7 },
      { label: "FY23", revenue: 58, ebitda: 11.8, ebitdaMargin: 20.3 },
      { label: "LTM", revenue: 78, ebitda: 19.5, ebitdaMargin: 25.0 },
      { label: "FY24E", revenue: 104, ebitda: 30, ebitdaMargin: 28.8 },
    ],
    ltmEbitda: 19.5,
    ltmRevenue: 78,
    totalLeverage: 5.6,
    seniorLeverage: 5.6,
    ltv: 38,
    fixedChargeCoverage: 1.6,
    blendedYield: 12.1,
    blendedSpread: 700,
    capitalStructure: [
      {
        id: "rcf",
        name: "Revolver",
        type: "Revolver",
        amountMM: 15,
        rate: "S+575",
        floor: "1.00%",
        maturityYears: 5,
        seniority: 1,
      },
      {
        id: "ut",
        name: "Senior Secured Unitranche",
        type: "Unitranche",
        amountMM: 110,
        rate: "S+700",
        floor: "1.00%",
        oid: "2.50%",
        maturityYears: 6,
        seniority: 1,
        ourHoldMM: 110,
        call: "NC2, 103, 101",
      },
      {
        id: "eq",
        name: "Sponsor Equity",
        type: "Equity",
        amountMM: 175,
        rate: "—",
        maturityYears: 0,
        seniority: 99,
      },
    ],
    diligence: [
      {
        id: "1",
        workstream: "Financial",
        task: "ARR roll-forward and cohort analysis",
        owner: "RSM",
        status: "In Progress",
        dueDate: "2026-05-15",
      },
      {
        id: "2",
        workstream: "Commercial",
        task: "MGA customer interviews (top 30)",
        owner: "Bain",
        status: "In Progress",
        dueDate: "2026-05-18",
      },
      {
        id: "3",
        workstream: "Operational",
        task: "Tech / security audit",
        owner: "Crowdstrike",
        status: "Not Started",
        dueDate: "2026-05-22",
      },
      {
        id: "4",
        workstream: "Legal",
        task: "Credit agreement first draft",
        owner: "Ropes & Gray",
        status: "In Progress",
        dueDate: "2026-05-21",
      },
    ],
    risks: [
      {
        category: "Market",
        severity: "Medium",
        description: "P&C insurance pricing softening could pressure MGA volumes.",
        mitigant: "Subscription pricing model insulates from premium volatility.",
      },
      {
        category: "Credit",
        severity: "Medium",
        description: "5.6x leverage on a software business at scale transition.",
        mitigant:
          "Recurring revenue 94%+, LTV/CAC > 5x, low-30s LTV provides equity cushion.",
      },
    ],
    keyTerms: [
      { label: "Maturity", value: "6 years" },
      { label: "Amortization", value: "1% per annum" },
      { label: "Call Protection", value: "NC2, 103, 101" },
      { label: "MFN", value: "100 bps, 24 months" },
    ],
    covenants: [
      { name: "Recurring Revenue Leverage", threshold: "≤ 1.75x ARR" },
      { name: "Min Liquidity", threshold: "$10MM" },
    ],
    expectedClose: "2026-06-30",
    leadAnalyst: "M. Chen",
    thesis:
      "Mission-critical vertical SaaS with high switching costs, strong cohort retention, and clear path to 30%+ EBITDA margins. Recurring-revenue-leverage structure with low LTV provides strong downside protection.",
  },
  {
    id: "harbor",
    code: "PROJ-HARBOR",
    borrowerName: "Harbor Specialty Foods",
    description:
      "Premium specialty foods manufacturer with branded and private-label exposure across grocery and foodservice.",
    sector: "Consumer",
    geography: "United States",
    stage: "Screening",
    sponsor: {
      name: "Coastal Capital",
      type: "Sponsor-backed",
      fundSize: 850,
    },
    useOfProceeds: "Dividend Recap",
    totalDealSizeMM: 220,
    ourCommitmentMM: 75,
    financials: [
      { label: "FY22", revenue: 168, ebitda: 22, ebitdaMargin: 13.1 },
      { label: "FY23", revenue: 184, ebitda: 27, ebitdaMargin: 14.7 },
      { label: "LTM", revenue: 196, ebitda: 31, ebitdaMargin: 15.8 },
    ],
    ltmEbitda: 31,
    ltmRevenue: 196,
    totalLeverage: 5.2,
    seniorLeverage: 4.4,
    ltv: 58,
    fixedChargeCoverage: 1.55,
    blendedYield: 11.6,
    blendedSpread: 625,
    capitalStructure: [],
    diligence: [],
    risks: [
      {
        category: "Market",
        severity: "Medium",
        description: "Input cost volatility (dairy, packaging) compressed margins in FY22.",
      },
      {
        category: "Credit",
        severity: "High",
        description: "Dividend recap removes ~$60MM of equity cushion.",
      },
    ],
    keyTerms: [],
    covenants: [],
    expectedClose: "2026-08-30",
    leadAnalyst: "J. Rivera",
    thesis:
      "Stable consumer staples cash flows with branded margins. Dividend recap leverage profile is at the upper end of our box; passing without meaningful coupon premium and tighter docs.",
  },
  {
    id: "summit",
    code: "PROJ-SUMMIT",
    borrowerName: "Summit Therapeutics Services",
    description:
      "Outsourced clinical research organization (CRO) servicing mid-cap pharma, ~$420MM revenue.",
    sector: "Healthcare",
    geography: "Global",
    stage: "Sourcing",
    sponsor: { name: "—", type: "Founder-led" },
    useOfProceeds: "Growth Capital",
    totalDealSizeMM: 320,
    ourCommitmentMM: 150,
    financials: [
      { label: "LTM", revenue: 420, ebitda: 68, ebitdaMargin: 16.2 },
    ],
    ltmEbitda: 68,
    ltmRevenue: 420,
    totalLeverage: 4.5,
    seniorLeverage: 4.5,
    ltv: 0,
    fixedChargeCoverage: 0,
    blendedYield: 11.0,
    blendedSpread: 575,
    capitalStructure: [],
    diligence: [],
    risks: [],
    keyTerms: [],
    covenants: [],
    expectedClose: "2026-10-15",
    leadAnalyst: "S. Park",
    thesis:
      "Founder-led CRO at attractive entry. Initial screen — pre-IOI, awaiting CIM and management meeting.",
  },
  {
    id: "vector",
    code: "PROJ-VECTOR",
    borrowerName: "Vector Industrial Components",
    description:
      "Roll-up of specialty industrial component distributors serving aerospace and defense aftermarket.",
    sector: "Industrials",
    geography: "United States",
    stage: "IOI",
    sponsor: {
      name: "Granite Peak Capital II",
      type: "Sponsor-backed",
      fundSize: 1450,
    },
    useOfProceeds: "LBO",
    totalDealSizeMM: 360,
    ourCommitmentMM: 175,
    financials: [
      { label: "FY22", revenue: 142, ebitda: 22, ebitdaMargin: 15.5 },
      { label: "FY23", revenue: 168, ebitda: 28, ebitdaMargin: 16.7 },
      { label: "LTM", revenue: 188, ebitda: 33, ebitdaMargin: 17.6 },
    ],
    ltmEbitda: 33,
    ltmRevenue: 188,
    totalLeverage: 5.0,
    seniorLeverage: 5.0,
    ltv: 51,
    fixedChargeCoverage: 1.7,
    blendedYield: 11.8,
    blendedSpread: 650,
    capitalStructure: [],
    diligence: [],
    risks: [],
    keyTerms: [],
    covenants: [],
    expectedClose: "2026-09-15",
    leadAnalyst: "M. Chen",
    thesis:
      "Defense aftermarket exposure provides recession-resilient demand. IOI submitted at S+650 unitranche.",
  },
  {
    id: "beacon",
    code: "PROJ-BEACON",
    borrowerName: "Beacon Wealth Advisors",
    description:
      "RIA aggregator with $14B AUM across 32 advisor practices.",
    sector: "Financial Services",
    geography: "United States",
    stage: "Closed",
    sponsor: {
      name: "Crestline Partners V",
      type: "Sponsor-backed",
      fundSize: 3100,
    },
    useOfProceeds: "Acquisition Financing",
    totalDealSizeMM: 280,
    ourCommitmentMM: 120,
    financials: [
      { label: "FY23", revenue: 102, ebitda: 38, ebitdaMargin: 37.3 },
      { label: "LTM", revenue: 118, ebitda: 46, ebitdaMargin: 39.0 },
    ],
    ltmEbitda: 46,
    ltmRevenue: 118,
    totalLeverage: 4.2,
    seniorLeverage: 4.2,
    ltv: 35,
    fixedChargeCoverage: 2.1,
    blendedYield: 11.2,
    blendedSpread: 600,
    capitalStructure: [],
    diligence: [],
    risks: [],
    keyTerms: [],
    covenants: [],
    expectedClose: "2026-02-20",
    leadAnalyst: "S. Aggarwal",
    thesis:
      "Closed Feb 2026. Performing in line with base case; Q1 EBITDA $12.4MM vs. plan $11.8MM.",
  },
  {
    id: "ironwood",
    code: "PROJ-IRONWOOD",
    borrowerName: "Ironwood Building Products",
    description:
      "Manufacturer of engineered wood products serving residential construction.",
    sector: "Industrials",
    geography: "United States",
    stage: "Passed",
    sponsor: { name: "Tallwood Capital", type: "Sponsor-backed", fundSize: 600 },
    useOfProceeds: "LBO",
    totalDealSizeMM: 180,
    ourCommitmentMM: 0,
    financials: [
      { label: "LTM", revenue: 215, ebitda: 24, ebitdaMargin: 11.2 },
    ],
    ltmEbitda: 24,
    ltmRevenue: 215,
    totalLeverage: 6.2,
    seniorLeverage: 6.2,
    ltv: 62,
    fixedChargeCoverage: 1.25,
    blendedYield: 10.8,
    blendedSpread: 550,
    capitalStructure: [],
    diligence: [],
    risks: [],
    keyTerms: [],
    covenants: [],
    expectedClose: "—",
    leadAnalyst: "J. Rivera",
    thesis:
      "Passed at IOI — leverage and end-market cyclicality exceeded our box. Pricing did not adequately compensate for risk.",
  },
];

export function getDeal(id: string) {
  return deals.find((d) => d.id === id);
}
