"use client";
import { Card, Tag, Typography } from "antd";
import Link from "next/link";
import type {
  ColDef,
  ICellRendererParams,
  ValueFormatterParams,
} from "ag-grid-community";
import { DataGrid } from "@/components/DataGrid";
import { deals } from "@/lib/data";

type MemoStatus = "Approved" | "Under Review" | "Draft";

interface MemoRow {
  id: string;
  dealId: string;
  borrowerName: string;
  code: string;
  generatedDate: string; // ISO
  generatedBy: string;
  status: MemoStatus;
}

const byCode = (code: string) => deals.find((d) => d.code === code);

const memoSeed: Array<{
  code: string;
  generatedDate: string;
  generatedBy: string;
  status: MemoStatus;
}> = [
  {
    code: "PROJ-MERIDIAN",
    generatedDate: "2026-04-28",
    generatedBy: "S. Park",
    status: "Under Review",
  },
  {
    code: "PROJ-ATLAS",
    generatedDate: "2026-04-22",
    generatedBy: "S. Aggarwal",
    status: "Draft",
  },
  {
    code: "PROJ-KESTREL",
    generatedDate: "2026-04-19",
    generatedBy: "M. Chen",
    status: "Draft",
  },
  {
    code: "PROJ-BEACON",
    generatedDate: "2026-02-08",
    generatedBy: "S. Aggarwal",
    status: "Approved",
  },
  {
    code: "PROJ-VECTOR",
    generatedDate: "2026-04-12",
    generatedBy: "M. Chen",
    status: "Draft",
  },
  {
    code: "PROJ-HARBOR",
    generatedDate: "2026-04-02",
    generatedBy: "J. Rivera",
    status: "Draft",
  },
  {
    code: "PROJ-IRONWOOD",
    generatedDate: "2026-03-14",
    generatedBy: "J. Rivera",
    status: "Approved",
  },
];

const memos: MemoRow[] = memoSeed
  .map((m) => {
    const d = byCode(m.code);
    if (!d) return null;
    return {
      id: `memo-${d.id}`,
      dealId: d.id,
      borrowerName: d.borrowerName,
      code: d.code,
      generatedDate: m.generatedDate,
      generatedBy: m.generatedBy,
      status: m.status,
    };
  })
  .filter((x): x is MemoRow => x !== null);

const statusColor: Record<MemoStatus, string> = {
  Approved: "green",
  "Under Review": "gold",
  Draft: "default",
};

const fmtDate = (params: ValueFormatterParams) => {
  const v = params.value as string;
  if (!v || v === "—") return "—";
  return new Date(v).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
};

const DealRenderer = (params: ICellRendererParams<MemoRow>) => {
  const m = params.data;
  if (!m) return null;
  return (
    <div style={{ lineHeight: 1.2 }}>
      <div style={{ fontWeight: 500, color: "#0f172a" }}>{m.borrowerName}</div>
      <div
        style={{
          fontSize: 11,
          color: "#64748b",
          fontFamily: "var(--font-geist-mono), ui-monospace, monospace",
        }}
      >
        {m.code}
      </div>
    </div>
  );
};

const StatusRenderer = (params: ICellRendererParams<MemoRow>) => (
  <Tag color={statusColor[params.value as MemoStatus]}>{params.value}</Tag>
);

const ViewMemoRenderer = (params: ICellRendererParams<MemoRow>) => {
  const id = params.data?.dealId;
  if (!id) return null;
  return (
    <Link
      href={`/deals/${id}?tab=memo`}
      style={{
        color: "#1677ff",
        fontSize: 13,
      }}
    >
      View Memo
    </Link>
  );
};

export default function MemosPage() {
  const columnDefs: ColDef<MemoRow>[] = [
    {
      field: "borrowerName",
      headerName: "Deal",
      flex: 2,
      minWidth: 220,
      cellRenderer: DealRenderer,
      filter: "agTextColumnFilter",
    },
    {
      field: "generatedDate",
      headerName: "Date Generated",
      width: 160,
      type: "numericColumn",
      cellClass: "ag-right-aligned-cell",
      valueFormatter: fmtDate,
    },
    {
      field: "generatedBy",
      headerName: "Generated By",
      width: 160,
      filter: "agTextColumnFilter",
    },
    {
      field: "status",
      headerName: "Status",
      width: 140,
      cellRenderer: StatusRenderer,
      filter: "agTextColumnFilter",
    },
    {
      colId: "view",
      headerName: "",
      width: 130,
      cellClass: "ag-right-aligned-cell",
      cellRenderer: ViewMemoRenderer,
      sortable: false,
      filter: false,
    },
  ];

  return (
    <div style={{ padding: 16 }}>
      <Typography.Title level={4} style={{ marginTop: 0, marginBottom: 12 }}>
        IC Memos
      </Typography.Title>

      <Card
        title="Generated Memos"
        size="small"
        extra={
          <Typography.Text type="secondary" style={{ fontSize: 11 }}>
            {memos.length} memos
          </Typography.Text>
        }
        styles={{ body: { padding: 0 } }}
      >
        <DataGrid<MemoRow>
          rowData={memos}
          columnDefs={columnDefs}
          getRowId={(p) => p.data.id}
        />
      </Card>
    </div>
  );
}
